apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: rminz/br-application
      docker:
        dockerfile: ci/Dockerfile
      context: .
      platforms:
        - linux/arm64
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  local:
    push: true
manifests:
  helm:
    releases:
      - name: "{{.ENVIRONMENT}}"
        chartPath: ci/charts/BR
        setValueTemplates:
          global.environment: "{{.ENVIRONMENT}}"
          global.region: "{{.REGION}}"
          global.image.repository: "{{.IMAGE_REPO}}"
          global.image.tag: "{{.ENVIRONMENT}}"
          global.image.digest: "{{.IMAGE_DIGEST}}"
          global.version: "{{.GIT_REV}}"
