apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-preview
  namespace: {{ $.Values.global.service }}
  labels:
    {{- include "br.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "br.selectorLabels" $ | nindent 6 }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
