name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  RE_BOT: ${{ secrets.RE_BOT }}
jobs:
  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}


      - name: Setup just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.3
        with:
          skaffold: "2.0.1"
          helm: "3.10.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rminz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Skaffold Cache
        uses: actions/cache@v3.0.11
        with:
          path: ~/.skaffold/
          key: skaffold-cache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            skaffold-cache-${{ github.ref_name }}-${{ github.sha }}
            skaffold-cache-${{ github.ref_name }}
            skaffold-cache-

      - name: Build and Push
        run: |-
          just build
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.3
        with:
          skaffold: "2.0.1"
          helm: "3.10.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rminz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Skaffold Cache
        uses: actions/cache@v3.0.11
        with:
          path: ~/.skaffold/
          key: skaffold-cache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            skaffold-cache-${{ github.ref_name }}-${{ github.sha }}
            skaffold-cache-${{ github.ref_name }}
            skaffold-cache-

      - name: Build and Push
        run: |-
          just build
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Kubernetes Tools
        uses: yokawasa/action-setup-kube-tools@v0.8.3
        with:
          skaffold: "2.0.1"
          helm: "3.10.0"

      - name: Deploy
        run: |-
          just gitops-repo-clone
          just apply prod europe-west4
